# Check http-client.env.json for live hostname
@hostname=http://127.0.0.1:8000

### register
POST {{hostname}}/api/register
Content-Type: application/json

{
    "name": "Leonardo",
    "email": "leonardoamx@outlook.com",
    "password": "kYEhQgsvHo43DmtjUeb2PFre9rUyughV"
}


### login
POST {{hostname}}/api/login
Content-Type: application/json

{
    "email": "leonardoamx@outlook.com",
    "password": "kYEhQgsvHo43DmtjUeb2PFre9rUyughV"
}


### me
GET {{hostname}}/api/me
Authorization: Bearer [token]


### logout
POST {{hostname}}/api/logout
Authorization: Bearer [token]


# CatAPI

### cats
GET {{hostname}}/api/cats/

### cats with page size
GET {{hostname}}/api/cats/?limit=5&page=0

### cats with page size and breed ID
GET {{hostname}}/api/cats/?limit=5&page=0&breed_ids=abys


### breeds
GET {{hostname}}/api/cats/breeds
